// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServerStatus is the runtime status of one configured MCP server.
 */
export interface ServerStatus {
    "id": string;
    "name": string;

    /**
     * stopped | connected | error
     */
    "state": string;
    "tools": ToolInfo[] | null;
    "error"?: string;
    "checkedAt": string;
}

/**
 * ToolInfo describes a tool exposed by a connected MCP server.
 */
export interface ToolInfo {
    "name": string;
    "description": string;
}
