// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService exposes generic app info.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * AppInfo returns static app metadata.
 */
export function AppInfo(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(1810596567);
}
