// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArtifactService previews workspace files produced by tool calls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List returns previewable files under the workspace (newest first, capped).
 */
export function List(): $CancellablePromise<$models.ArtifactInfo[] | null> {
    return $Call.ByID(2323643321);
}

/**
 * Open reads a workspace file for preview. Path is relative to the workspace.
 */
export function Open(relPath: string): $CancellablePromise<$models.Artifact | null> {
    return $Call.ByID(2472935809, relPath);
}

/**
 * Workspace returns the configured workspace directory (for UI display).
 */
export function Workspace(): $CancellablePromise<string> {
    return $Call.ByID(3216171198);
}
