// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService manages chat sessions and streaming runs over ADK.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel aborts the in-flight run of a session, if any.
 */
export function Cancel(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3046108191, sessionID);
}

/**
 * DeleteSession removes a chat and its stored events.
 */
export function DeleteSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(2720233066, id);
}

/**
 * ExportSession writes the conversation as Markdown into the workspace export
 * directory and returns the file path.
 */
export function ExportSession(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(3243786305, sessionID);
}

/**
 * GetSessionMessages renders the stored ADK events for a session.
 */
export function GetSessionMessages(sessionID: string): $CancellablePromise<$models.ChatMessage[] | null> {
    return $Call.ByID(3662319581, sessionID);
}

/**
 * IsRunning reports whether a session currently has an in-flight run.
 */
export function IsRunning(sessionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3574706456, sessionID);
}

/**
 * ListSessions returns all chat sessions, newest first.
 */
export function ListSessions(): $CancellablePromise<config$0.ChatSession[] | null> {
    return $Call.ByID(1516353476);
}

/**
 * NewSession creates a chat bound to an agent or team.
 */
export function NewSession(targetType: string, targetID: string, title: string): $CancellablePromise<config$0.ChatSession> {
    return $Call.ByID(3793260767, targetType, targetID, title);
}

/**
 * Regenerate redoes the last user turn: it trims the trailing conversation
 * (from the last user message onward, inclusive) and re-runs the same message.
 */
export function Regenerate(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(368507619, sessionID);
}

/**
 * RenameSession updates a session title.
 */
export function RenameSession(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(3416606985, id, title);
}

/**
 * Send runs one user turn against the session's target agent/team. It blocks
 * until the run completes and streams progress via chat:stream events.
 */
export function Send(sessionID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1748553651, sessionID, text);
}
