// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes configuration CRUD to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * DeleteAgent removes an agent and detaches it from teams.
 */
export function DeleteAgent(id: string): $CancellablePromise<void> {
    return $Call.ByID(3938069995, id);
}

/**
 * DeleteMCPServer removes an MCP server and detaches it from agents.
 */
export function DeleteMCPServer(id: string): $CancellablePromise<void> {
    return $Call.ByID(22452925, id);
}

/**
 * DeleteProvider removes a provider by id.
 */
export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(3002230555, id);
}

/**
 * DeleteSkill removes a skill by id.
 */
export function DeleteSkill(id: string): $CancellablePromise<void> {
    return $Call.ByID(3210932935, id);
}

/**
 * DeleteTeam removes a team by id.
 */
export function DeleteTeam(id: string): $CancellablePromise<void> {
    return $Call.ByID(661470679, id);
}

/**
 * GetConfig returns the full configuration (API keys included; local app).
 */
export function GetConfig(): $CancellablePromise<config$0.Config> {
    return $Call.ByID(362021961);
}

/**
 * ListProviderModels fetches the model IDs offered by the provider's list
 * endpoint, so the user can pick instead of typing model ids by hand.
 */
export function ListProviderModels(p: config$0.ModelProvider): $CancellablePromise<Array<string>> {
    return $Call.ByID(2350675726, p);
}

/**
 * SaveAgent inserts or updates an agent.
 */
export function SaveAgent(a: config$0.AgentConfig): $CancellablePromise<void> {
    return $Call.ByID(482075013, a);
}

/**
 * SaveMCPServer inserts or updates an MCP server config.
 */
export function SaveMCPServer(s: config$0.MCPServerConfig): $CancellablePromise<void> {
    return $Call.ByID(2532663851, s);
}

/**
 * SaveProvider inserts or updates a model provider.
 */
export function SaveProvider(p: config$0.ModelProvider): $CancellablePromise<void> {
    return $Call.ByID(488827929, p);
}

/**
 * SaveSettings persists global settings.
 */
export function SaveSettings(s: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(2460420529, s);
}

/**
 * SaveSkill inserts or updates a skill (materialized to SKILL.md).
 */
export function SaveSkill(s: config$0.SkillConfig): $CancellablePromise<void> {
    return $Call.ByID(3441334657, s);
}

/**
 * SaveTeam inserts or updates an agent team.
 */
export function SaveTeam(t: config$0.TeamConfig): $CancellablePromise<void> {
    return $Call.ByID(2557233981, t);
}

/**
 * TestProvider performs a minimal round-trip against the provider with the
 * chosen model to verify reachability and credentials.
 */
export function TestProvider(p: config$0.ModelProvider, model: string): $CancellablePromise<void> {
    return $Call.ByID(1354150776, p, model);
}
