// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPService exposes MCP server management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcpmgr$0 from "../mcpmgr/models.js";

/**
 * Connect starts/verifies the connection for one MCP server and returns its
 * status including the discovered tool list.
 */
export function Connect(id: string): $CancellablePromise<mcpmgr$0.ServerStatus> {
    return $Call.ByID(3458547111, id);
}

/**
 * Disconnect drops the connection state of one MCP server.
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(1232363321, id);
}

/**
 * Status returns the current status of all configured MCP servers.
 */
export function Status(): $CancellablePromise<mcpmgr$0.ServerStatus[] | null> {
    return $Call.ByID(1089169061);
}
