// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Artifact is a previewable file from the workspace.
 */
export interface Artifact {
    "name": string;

    /**
     * relative to the workspace
     */
    "path": string;

    /**
     * image|markdown|text|pdf|binary
     */
    "kind": string;
    "mime": string;
    "size": number;

    /**
     * image/pdf (base64 data URL)
     */
    "dataUrl"?: string;

    /**
     * text/markdown/code
     */
    "text"?: string;
    "truncated": boolean;
}

/**
 * ArtifactInfo is a lightweight listing entry.
 */
export interface ArtifactInfo {
    "name": string;
    "path": string;
    "kind": string;
    "size": number;
}

/**
 * ChatMessage is a rendered historical message.
 */
export interface ChatMessage {
    "id": string;

    /**
     * user|message|tool_call|tool_result
     */
    "kind": string;
    "author": string;
    "text": string;
    "toolName"?: string;
    "toolArgs"?: { [_ in string]?: any } | null;
    "toolResp"?: { [_ in string]?: any } | null;
    "timestamp": string;
}

/**
 * ChatStreamEvent is streamed to the frontend while a run progresses.
 */
export interface ChatStreamEvent {
    "sessionId": string;

    /**
     * user|delta|message|tool_call|tool_result|done|error
     */
    "kind": string;
    "author": string;
    "text": string;
    "toolName"?: string;
    "toolArgs"?: { [_ in string]?: any } | null;
    "toolResp"?: { [_ in string]?: any } | null;

    /**
     * Usage is set on the final assistant message event of a turn.
     */
    "usage"?: UsageInfo | null;

    /**
     * SessionUsage is the cumulative usage of the session, set on done events.
     */
    "sessionUsage"?: UsageInfo | null;
}

/**
 * UsageInfo reports token consumption for a turn or a whole session.
 */
export interface UsageInfo {
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;
}
