// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentConfig describes a user-defined agent.
 */
export interface AgentConfig {
    "id": string;
    "name": string;
    "description": string;
    "providerId": string;
    "model": string;
    "systemPrompt": string;
    "temperature": number;
    "maxTokens": number;

    /**
     * skills attached to this agent
     */
    "skillIds": string[] | null;

    /**
     * MCP servers whose tools are available
     */
    "mcpServerIds": string[] | null;

    /**
     * subset of builtin tool names: time, files, knowledge
     */
    "builtinTools": string[] | null;
    "createdAt": string;

    /**
     * EnableGuardrails masks secrets in user input/model output (default on
     * when unset). Pointers distinguish "unset" from explicit false.
     */
    "enableGuardrails"?: boolean | null;
}

/**
 * ChatSession is a chat conversation bound to an agent or a team.
 */
export interface ChatSession {
    "id": string;
    "title": string;

    /**
     * "agent" | "team"
     */
    "targetType": string;
    "targetId": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Config is the root configuration document persisted to disk.
 */
export interface Config {
    "settings": Settings;
    "providers": ModelProvider[] | null;
    "agents": AgentConfig[] | null;
    "teams": TeamConfig[] | null;
    "skills": SkillConfig[] | null;
    "mcpServers": MCPServerConfig[] | null;
    "sessions": ChatSession[] | null;
}

/**
 * MCPServerConfig describes an MCP server connection.
 */
export interface MCPServerConfig {
    "id": string;
    "name": string;
    "transport": MCPTransport;

    /**
     * stdio
     */
    "command": string;

    /**
     * stdio
     */
    "args": string[] | null;

    /**
     * stdio
     */
    "env"?: { [_ in string]?: string } | null;

    /**
     * streamable-http
     */
    "url": string;

    /**
     * streamable-http
     */
    "headers"?: { [_ in string]?: string } | null;
    "autoStart": boolean;
}

/**
 * MCPTransport selects how the MCP server is reached.
 */
export enum MCPTransport {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MCPStdio = "stdio",
    MCPStreamableHTTP = "streamable-http",
};

/**
 * ModelProvider describes a configurable LLM provider endpoint.
 */
/**
 * ModelInfo describes a model exposed by a provider.
 */
export interface ModelInfo {
    "id": string;

    /**
     * Multimodal marks models that accept image input; the chat UI uses it
     * to enable the image attachment button.
     */
    "multimodal"?: boolean;

    /**
     * ContextWindow is the model's input context size in tokens (0 = unknown).
     */
    "contextWindow"?: number;

    /**
     * PriceIn/PriceOut are optional prices per 1M tokens (input/output),
     * used for cost estimation in the chat UI.
     */
    "priceIn"?: number;
    "priceOut"?: number;
}

export interface ModelProvider {
    "id": string;
    "name": string;
    "protocol": Protocol;
    "baseUrl": string;
    "apiKey": string;

    /**
     * model ids usable with this provider
     */
    "models": ModelInfo[] | null;
    "isDefault": boolean;

    /**
     * PriceIn/PriceOut are the legacy provider-level prices. They are copied
     * down to each model and cleared on load (migrateLegacy); kept only so
     * old config files migrate instead of losing data.
     */
    "priceIn"?: number;
    "priceOut"?: number;
}

/**
 * Protocol enumerates the LLM API protocols supported by the app.
 */
export enum Protocol {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * OpenAI Chat Completions compatible (OpenAI, DeepSeek, Kimi, Ollama, vLLM...)
     */
    ProtocolOpenAI = "openai",

    /**
     * Anthropic Messages API (Claude)
     */
    ProtocolAnthropic = "anthropic",

    /**
     * Google Gemini API
     */
    ProtocolGemini = "gemini",
};

/**
 * Settings holds global application settings.
 */
export interface Settings {
    "workspaceDir": string;
    "language": string;

    /**
     * Appearance: theme mode "light"|"dark"|"system", accent key, font scale
     * "sm"|"md"|"lg", and whether to speak assistant replies automatically.
     */
    "themeMode": string;
    "accent": string;
    "fontScale": string;
    "autoSpeak": boolean;
}

/**
 * SkillConfig is a reusable instruction bundle (agentskills.io SKILL.md).
 */
export interface SkillConfig {
    "id": string;
    "name": string;
    "description": string;

    /**
     * markdown body of the skill
     */
    "content": string;
    "createdAt": string;
}

/**
 * TeamConfig describes an agent team: a lead agent coordinating member agents.
 */
export interface TeamConfig {
    "id": string;
    "name": string;
    "description": string;

    /**
     * empty => auto coordinator
     */
    "leadAgentId": string;

    /**
     * synthesize a coordinator instead of using a member as lead
     */
    "autoCoordinate": boolean;
    "memberAgentIds": string[] | null;

    /**
     * used by the auto coordinator
     */
    "providerId": string;
    "model": string;
    "systemPrompt": string;
    "createdAt": string;
}
